### ISSUE TITLE
Unable to run the package with no replicates 

### ISSUE THREAD

**Issue by huangxingnan1994** [dpeerlab/Palantir#19] opened 2019-09-02 17:11 UTC
Hey, it's a great package! When running `pr_res = palantir.core.run_palantir(ms_data,start_cell,end_cell,use_early_cell_as_start=True,n_jobs=10)` I have a problem as follow:

<img width="1645" alt="Screen Shot 2019-09-03 at 1 02 32 AM" src="https://user-images.githubusercontent.com/53215509/64128019-de76a380-cde6-11e9-8202-7c974780e632.png">

<img width="1645" alt="Screen Shot 2019-09-03 at 1 09 17 AM" src="https://user-images.githubusercontent.com/53215509/64128127-83917c00-cde7-11e9-990b-4b7c690f5e56.png">
<img width="1554" alt="Screen Shot 2019-09-03 at 1 10 21 AM" src="https://user-images.githubusercontent.com/53215509/64128155-a6bc2b80-cde7-11e9-8c4b-710f36d189b8.png">

**Comment by ManuSetty** [comment] 2019-09-03 01:24
What is the value of the `end_cell` parameter you are using? The `terminal_states` parameter needs to a list or an array, so if `end_cell` is one single cell, can you try again by using `[end_cell]` instead ?

**Comment by huangxingnan1994** [comment] 2019-09-03 08:34
This is what I give to end_cells:
`end_cells = ['PNT_D8_Day8_GGTGCGTGTATCTGCA-1','PNT_D5_Day5_AGAATAGGTATATCCG-1']`
They are not a single cell.

**Comment by huangxingnan1994** [comment] 2019-09-03 08:35
This is what I give to end_cell:
`end_cell = ['PNT_D8_Day8_GGTGCGTGTATCTGCA-1','PNT_D5_Day5_AGAATAGGTATATCCG-1']`
They are not a single cell.

**Comment by huangxingnan1994** [comment] 2019-09-03 13:56
My single-cell data do not have biological replicates. I wonder if it is problem about replicates.

**Comment by huangxingnan1994** [comment] 2019-09-03 14:15
When I ran code in your palantir notebook, the same issue happened again.
I did not change your code.
<img width="1687" alt="Screen Shot 2019-09-03 at 10 11 53 PM" src="https://user-images.githubusercontent.com/53215509/64180730-df1b4280-ce97-11e9-9359-59d970995f34.png">

**Comment by ManuSetty** [comment] 2019-09-03 20:53
Having no replicates should not be an issue here. I am unfortunately unable to reproduce the error with the sample dataset provided. Can you let me know the versions of `python, pandas, numpy and scipy`

**Comment by huangxingnan1994** [comment] 2019-09-04 03:05
python 3.7.3
pandas 0.25.0
numpy 1.17.0
scipy 1.3.1

**Comment by ManuSetty** [comment] 2019-09-04 13:12
Sorry - still unable to reproduce the error with the same versions of the modules. Are you modifying the row indexes in any manner in your analysis?

**Comment by huangxingnan1994** [comment] 2019-09-04 13:20
My dataset looks like as the following pictures
<img width="1609" alt="Screen Shot 2019-09-04 at 9 16 59 PM" src="https://user-images.githubusercontent.com/53215509/64258313-9af07680-cf59-11e9-9fad-eada67668581.png">

**Comment by ManuSetty** [comment] 2019-09-04 13:37
Can you send me the output of this command: `np.where(ms_data.index.isin(end_cell))`. I want to make sure that end cells are not getting messed because of some inadvertent formatting.

**Comment by huangxingnan1994** [comment] 2019-09-05 03:42
This is the output. Is it what you want?

<img width="1091" alt="Screen Shot 2019-09-05 at 11 41 28 AM" src="https://user-images.githubusercontent.com/53215509/64310297-27d71680-cfd2-11e9-9f7e-9247fa5b6fa1.png">

**Comment by ManuSetty** [comment] 2019-09-05 23:11
Yes, this is what I wanted to see but I am afraid I am not sure at all as to why you are getting these errors. Could you perhaps try re-installing Palantir again?

**Comment by huangxingnan1994** [comment] 2019-09-07 03:49
Yes . After re-installing the anaconda and package, it works well. I can obtain the plots. Thanks you, ManuSetty!

**Comment by ManuSetty** [comment] 2019-09-07 05:27
Glad to hear - closing the issue,

**Closed by ManuSetty** 2019-09-07 05:27 UTC
